const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const INCREMENT_PRODUCT = "INCREMENT_PRODUCT";
const DECREMENT_PRODUCT = "DECREMENT_PRODUCT";
const BUY_NOW_ACTION = "BUY_NOW_ACTION";
const BUY_ACTION = "BUY_ACTION";
const PLACE_ORDER = "PLACE_ORDER";
const GET_PRODUCTS = "GET_PRODUCTS";
const LOG_IN_USER = "LOG_IN_USER";
const LOG_OUT_USER = "LOG_OUT_USER";
const EMPTY_CART = "EMPTY_CART";

export {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  INCREMENT_PRODUCT,
  DECREMENT_PRODUCT,
  BUY_NOW_ACTION,
  BUY_ACTION,
  PLACE_ORDER,
  GET_PRODUCTS,
  LOG_IN_USER,
  LOG_OUT_USER,
  EMPTY_CART,
};
